apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-config
  namespace: llm-platform
data:
  opt-chat-template.jinja: |
    {% for message in messages %}
    {% if message['role'] == 'system' -%}
    System: {{ message['content'] }}
    {% elif message['role'] == 'user' -%}
    User: {{ message['content'] }}
    {% elif message['role'] == 'assistant' -%}
    Assistant: {{ message['content'] }}
    {% endif -%}
    {% endfor -%}
    {% if add_generation_prompt -%}
    Assistant:
    {% endif -%}
